import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const titleOtf = localFont({
  src: "./fonts/ChungjuKimSaeng.otf",
  variable: "--font-title-otf",
  weight: "100 900",
});
const contentBatang = localFont({
  src: "./fonts/GowunBatang-Bold.ttf",
  variable: "--font-content-batang",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${titleOtf.variable} ${contentBatang.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
